version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - terraform_data:/app/terraform
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  cache:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  terraform_data:
  redis_data:

networks:
  backend_net:
    driver: overlay
    driver_opts:
      encrypted: "true"