// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://ouinsnwnqndchqtcxhpr.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91aW5zbnducW5kY2hxdGN4aHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MTc5NTcsImV4cCI6MjA1MjM5Mzk1N30.p4C452_zsU_6BiPtzZ4PLDgNc4uW2Jc4z3WZGrdaeAY';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
